# Generated by Django 4.2 on 2023-05-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
    ]
